=== caatdata/arms-and-security-fair-exhibitors/schema/fair.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Fair",
  "description": "A single arms and security fair, possibly including exhibitors and/or delegations.",
  "definitions": {
    "text": {
      "description": "A non-empty string.",
      "type": "string",
      "pattern": "^."
    },
    "textOrTextArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/text"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/text"
          }
        }
      ]
    },
    "url": {
      "$comment": "Poor source data will not pass even the simplest URL regex rule.",
      "type": "string"
    },
    "urlOrUrlArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/url"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/url"
          }
        }
      ]
    },
    "dateString": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
    },
    "dateStringPartial": {
      "type": "string",
      "pattern": "^[0-9]{4}(-[0-9]{2}){0,2}$"
    },
    "utcDatetimeString": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\+00:00$"
    },
    "iso2": {
      "type": "string",
      "pattern": "^[A-Z]{2}$"
    },
    "address": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "iso2": {
              "$ref": "#/definitions/iso2"
            },
            "lat": {
              "type": "number",
              "minimum": -90,
              "maximum": 90
            },
            "lon": {
              "type": "number",
              "minimum": -180,
              "maximum": 180
            }
          },
          "required": [
            "text",
            "iso2",
            "lat",
            "lon"
          ],
          "additionalProperties": false
        }
      ]
    },
    "addressOrAddressArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/address"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/address"
          }
        }
      ]
    },
    "country": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "iso2": {
              "$ref": "#/definitions/iso2"
            }
          },
          "required": [
            "text",
            "iso2"
          ],
          "additionalProperties": false
        }
      ]
    },
    "countryOrCountryArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/country"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/country"
          }
        }
      ]
    },
    "social": {
      "type": "object",
      "oneOf": [
        {
          "required": [
            "platform",
            "handle"
          ]
        },
        {
          "required": [
            "platform",
            "url"
          ]
        }
      ],
      "properties": {
        "platform": {
          "$ref": "#/definitions/text"
        },
        "handle": {
          "$ref": "#/definitions/text"
        },
        "url": {
          "$ref": "#/definitions/text"
        }
      }
    },
    "socialOrSocialArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/social"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/social"
          }
        }
      ]
    },
    "exhibitor": {
      "type": "object",
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "$ref": "#/definitions/text"
        },
        "alias": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "exhibitorUrl": {
          "$ref": "#/definitions/url"
        },
        "address": {
          "$ref": "#/definitions/addressOrAddressArray"
        },
        "country": {
          "$ref": "#/definitions/countryOrCountryArray"
        },
        "website": {
          "$ref": "#/definitions/urlOrUrlArray"
        },
        "email": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "telephone": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "social": {
          "$ref": "#/definitions/socialOrSocialArray"
        },
        "category": {
          "$ref": "#/definitions/textOrTextArray"
        }
      }
    },
    "organiser": {
      "type": "object",
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "$ref": "#/definitions/text"
        },
        "alias": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "address": {
          "$ref": "#/definitions/addressOrAddressArray"
        },
        "country": {
          "$ref": "#/definitions/countryOrCountryArray"
        },
        "website": {
          "$ref": "#/definitions/urlOrUrlArray"
        },
        "email": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "telephone": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "social": {
          "$ref": "#/definitions/socialOrSocialArray"
        }
      }
    }
  },
  "type": "object",
  "required": [
    "name"
  ],
  "oneOf": [
    {
      "required": [
        "startDate",
        "endDate"
      ]
    },
    {
      "required": [
        "approxDate"
      ]
    }
  ],
  "dependencies": {
    "exhibitor": [
      "exhibitorListDate"
    ],
    "delegation": [
      "delegationListDate"
    ]
  },
  "additionalProperties": false,
  "properties": {
    "name": {
      "$ref": "#/definitions/text"
    },
    "alias": {
      "$ref": "#/definitions/textOrTextArray"
    },
    "series": {
      "$ref": "#/definitions/text"
    },
    "edition": {
      "$ref": "#/definitions/text"
    },
    "startDate": {
      "$ref": "#/definitions/dateString"
    },
    "endDate": {
      "$ref": "#/definitions/dateString"
    },
    "approxDate": {
      "$ref": "#/definitions/dateStringPartial"
    },
    "address": {
      "$ref": "#/definitions/addressOrAddressArray"
    },
    "country": {
      "$ref": "#/definitions/countryOrCountryArray"
    },
    "online": {
      "type": "boolean"
    },
    "website": {
      "$ref": "#/definitions/urlOrUrlArray"
    },
    "social": {
      "$ref": "#/definitions/socialOrSocialArray"
    },
    "organiser": {
      "anyOf": [
        {
          "$ref": "#/definitions/organiser"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/organiser"
          }
        }
      ]
    },
    "exhibitorListUrl": {
      "$ref": "#/definitions/url"
    },
    "exhibitorListDate": {
      "$ref": "#/definitions/utcDatetimeString"
    },
    "exhibitor": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/exhibitor"
      }
    },
    "exhibitorListIncomplete": {
      "type": "boolean",
      "const": true
    },
    "delegationListUrl": {
      "$ref": "#/definitions/url"
    },
    "delegationListDate": {
      "$ref": "#/definitions/utcDatetimeString"
    },
    "delegation": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "$ref": "#/definitions/text"
          },
          "attended": {
            "type": "boolean"
          },
          "retracted": {
            "type": "boolean"
          }
        }
      }
    }
  }
}

=== caatdata/arms-and-security-fair-exhibitors/data/ifsec-europe-2016.json
{
  "name": "IFSEC International 2016",
  "series": "IFSEC International",
  "edition": "2016",
  "alias": "International Fire and Security Exhibition and Conference International 2016",
  "approxDate": "2016",
  "website": "https://www.ifsecglobal.com/event/en/home.html",
  "country": "United Kingdom"
}

=== caatdata/arms-and-security-fair-exhibitors/data/securex-south-africa-2009.json
{
  "name": "Securex South Africa 2009",
  "series": "Securex South Africa",
  "edition": "2009",
  "alias": [
    "IFSEC SA 2009",
    "IFSEC South Africa 2009"
  ],
  "startDate": "2009-06-30",
  "endDate": "2009-07-02",
  "address": {
    "text": "Gallagher Convention Centre\n19 Richards Drive\nMidrand\nJohannesburg\nSouth Africa",
    "iso2": "ZA",
    "lat": -26.0016667,
    "lon": 28.1297222
  },
  "website": "http://www.ifsecsa.com",
  "organiser": [
    {
      "name": "UBM",
      "website": "http://www.cmpi.biz/ubmlive"
    }
  ],
  "exhibitorListUrl": "http://www.ifsecsa.com",
  "exhibitorListDate": "2022-03-11T16:52:03+00:00",
  "exhibitor": [
    {
      "name": "ID Card Technologies"
    },
    {
      "name": "ADI"
    },
    {
      "name": "All Technologies Access Parking (Pty) Ltd"
    },
    {
      "name": "Audiosure"
    },
    {
      "name": "Axis Communications SA Pty Ltd"
    },
    {
      "name": "Centurion Systems"
    },
    {
      "name": "Classic Acoustics"
    },
    {
      "name": "Classic Systems"
    },
    {
      "name": "CIEFFE"
    },
    {
      "name": "Cochrane Steel Products"
    },
    {
      "name": "Connoisseur Electronics"
    },
    {
      "name": "Connoisseur Electronics"
    },
    {
      "name": "Control soft"
    },
    {
      "name": "Defence Concepts South Africa"
    },
    {
      "name": "Emergency Reaction Services"
    },
    {
      "name": "Fox Electronics"
    },
    {
      "name": "Frank Street"
    },
    {
      "name": "FSK"
    },
    {
      "name": "Gallagher Power"
    },
    {
      "name": "GeoVision South Africa"
    },
    {
      "name": "Global Armour"
    },
    {
      "name": "Global Communications"
    },
    {
      "name": "Guardtrack"
    },
    {
      "name": "HAB International Fire & Security (Pty) Ltd"
    },
    {
      "name": "Hid Global"
    },
    {
      "name": "Hudaco Trading (Pty) Ltd (Elvey)"
    },
    {
      "name": "Ideco Registration"
    },
    {
      "name": "Illuder"
    },
    {
      "name": "Imperial Armour"
    },
    {
      "name": "Impro"
    },
    {
      "name": "Industrial Automation"
    },
    {
      "name": "MAMI"
    },
    {
      "name": "Martin Electronics cc"
    },
    {
      "name": "Motorola"
    },
    {
      "name": "Multi Locking Vehicle Tracking Security"
    },
    {
      "name": "Nemtek"
    },
    {
      "name": "Network Video Tech"
    },
    {
      "name": "Norbain"
    },
    {
      "name": "Questek"
    },
    {
      "name": "R&D Screening Technologies"
    },
    {
      "name": "Regal Eltro Pty Ltd"
    },
    {
      "name": "Saflec / Saflec Systems"
    },
    {
      "name": "Sambane International"
    },
    {
      "name": "Sanyo"
    },
    {
      "name": "Security & Communication Warehouse"
    },
    {
      "name": "Senstar-Stellar Corporation"
    },
    {
      "name": "Sentronics"
    },
    {
      "name": "Sherlotronics"
    },
    {
      "name": "Space TV"
    },
    {
      "name": "Spectrum Communications"
    },
    {
      "name": "Stafix"
    },
    {
      "name": "Tele eye"
    },
    {
      "name": "Telkom"
    },
    {
      "name": "Therma Card"
    },
    {
      "name": "Trac - Tech"
    },
    {
      "name": "Transaction Control"
    },
    {
      "name": "Trinity Telecomms"
    },
    {
      "name": "Uniclox Technologies"
    },
    {
      "name": "Y- Cam"
    }
  ]
}

=== caatdata/arms-and-security-fair-exhibitors/data/nlw-2019.json
{
  "name": "NLW 2019",
  "series": "NLW",
  "alias": [
    "10th European Symposium on Non-Lethal Weapons"
  ],
  "edition": "2019",
  "startDate": "2019-05-20",
  "endDate": "2019-05-23",
  "address": {
    "text": "Royal Military Academy\nBrussels\nBelgium",
    "iso2": "BE",
    "lat": 50.8445816,
    "lon": 4.393333
  },
  "website": [
    "https://www.non-lethal-weapons.org/en/symposia/symposium-2018.html",
    "https://v3.globalcube.net/clients/ewgv1/content/medias/symposia/10_brussels/sy10programme.pdf"
  ],
  "organiser": [
    {
      "name": "European Working Group Non-Lethal Weapons",
      "website": "www.non-lethal-weapons.com"
    }
  ]
}

=== caatdata/arms-and-security-fair-exhibitors/data/isdef-2013.json
{
  "name": "ISDEF 2013",
  "series": "ISDEF",
  "edition": "2013",
  "alias": "International Defence and Homeland Security Expo 2013",
  "approxDate": "2013",
  "website": "https://www.isdefexpo.com/#:~:text=ISDEF%202021%20will%20bring%20together,transfer%20to%20ensure%20public%20safety.",
  "country": "Israel"
}

=== caatdata/arms-and-security-fair-exhibitors/data/securex-uzbekistan-2021.json
{
  "name": "Securex Uzbekistan 2021",
  "series": "Securex Uzbekistan",
  "edition": "2021",
  "alias": "12th Central Asian International Exhibition for Industrial Safety. Personal Protection Technologies. Equipment & systems for security & fire extinguishing. IT solutions. Data security",
  "startDate": "2021-11-03",
  "endDate": "2021-11-05",
  "address": "Tashkent\nUzbekistan",
  "website": "https://securex.uz/en/",
  "organiser": [
    {
      "name": "Iteca Exhibitions",
      "website": "https://iteca.uz",
      "social": [
        {
          "platform": "facebook",
          "url": "https://www.facebook.com/ItecaExhibitions/"
        },
        {
          "platform": "twitter",
          "url": "https://twitter.com/ItecaExhibition"
        }
      ]
    }
  ],
  "exhibitorListUrl": "https://www.securex.uz/en/exhibition/spisok-uchastnikov.php",
  "exhibitorListDate": "2022-03-13T13:05:55+00:00",
  "exhibitor": [
    {
      "name": "ASKARI SHOE PROJECT"
    },
    {
      "name": "AVANT GUARD, LLC"
    },
    {
      "name": "BRASSCO"
    },
    {
      "name": "DEFENCE EXPORT PROMOTION ORGANIZATION (DEPO)"
    },
    {
      "name": "ENERGOCONTRACT"
    },
    {
      "name": "EXPORT SUPPORT CENTER OF TOMSK REGION"
    },
    {
      "name": "HUAWEI TECH INVESTMENT TASHKENT, FE LLC"
    },
    {
      "name": "NATIONAL RADIO & TELECOMMUNICATION CORPORATION"
    },
    {
      "name": "NEW SOLUTION SERVICE, LLC"
    },
    {
      "name": "OLVIA"
    },
    {
      "name": "PAKISTAN MACHINE TOOL FACTORY (PVT) LTD"
    },
    {
      "name": "PAKISTAN ORDNANCE FACTORIES"
    },
    {
      "name": "POLIMASTER"
    },
    {
      "name": "REGULA"
    },
    {
      "name": "RUSSKAYA SVARKA, LLC"
    },
    {
      "name": "STAR LIGHT TECHNOLOGY"
    },
    {
      "name": "TBS INFORM, LLC"
    }
  ]
}

=== caatdata/arms-and-security-fair-exhibitors/data/ifsec-india-2008.json
{
  "name": "IFSEC India 2008",
  "series": "IFSEC India",
  "edition": "2008",
  "startDate": "2008-10-16",
  "endDate": "2008-10-18",
  "address": {
    "text": "Pragati Maidan\nNew Delhi\nIndia",
    "iso2": "IN",
    "lat": 28.6126456,
    "lon": 77.2433578
  },
  "website": "http://www.ifsecindia.com",
  "organiser": [
    {
      "name": "CMP Information",
      "website": "http://www.cmpi.biz"
    }
  ],
  "exhibitorListUrl": "http://www.ifsecindia.com/ifsec08/exhibitors.html?e",
  "exhibitorListDate": "2022-03-10T21:40:58+00:00",
  "exhibitor": [
    {
      "name": "A & S Group"
    },
    {
      "name": "A V Systems"
    },
    {
      "name": "ACTAtek Ltd"
    },
    {
      "name": "Adept Designs"
    },
    {
      "name": "ADI"
    },
    {
      "name": "Adion Technologies Pvt. Ltd."
    },
    {
      "name": "Adit Enterprise"
    },
    {
      "name": "Aditya Infotech Ltd."
    },
    {
      "name": "Adtech Systems Limited"
    },
    {
      "name": "Advanced Detection Technology"
    },
    {
      "name": "Advert Technologies"
    },
    {
      "name": "Al Waheed General Trading Co. (GBP)"
    },
    {
      "name": "Alba Urmet Comm & Security (P) Ltd."
    },
    {
      "name": "All e Technologies (P) Ltd."
    },
    {
      "name": "AMG Systems"
    },
    {
      "name": "Amron Associates Private Ltd."
    },
    {
      "name": "Aravli Hitech"
    },
    {
      "name": "Arise Security Systems"
    },
    {
      "name": "Arya Communications & Electronics Services Pvt. Lt"
    },
    {
      "name": "Asia Info Company Ltd"
    },
    {
      "name": "Asian Professional Security Association"
    },
    {
      "name": "Astraguard Pvt. Ltd"
    },
    {
      "name": "Autocop Security Solutions Pvt. Ltd."
    },
    {
      "name": "Axis Communication"
    },
    {
      "name": "AXVIEW TECHNOLOGY (SHENZHEN) CO., LTD"
    },
    {
      "name": "AXXON"
    },
    {
      "name": "BFT S.P.A."
    },
    {
      "name": "Bioinsec Co., Ltd"
    },
    {
      "name": "Bitron Video SRL"
    },
    {
      "name": "Biztradeshows.com"
    },
    {
      "name": "Bluecard Software Technology Co Ltd"
    },
    {
      "name": "C A Satyam ASP Pvt. Ltd."
    },
    {
      "name": "CBC Co. Ltd."
    },
    {
      "name": "CDVI"
    },
    {
      "name": "China Public Security"
    },
    {
      "name": "CIEFFE S.p.A"
    },
    {
      "name": "Comm Port Technologies Inc."
    },
    {
      "name": "Computer Recognition Systems"
    },
    {
      "name": "COP SECURITY SYSTEM CORP."
    },
    {
      "name": "Cradle Technologies India Pvt. Ltd."
    },
    {
      "name": "Crockett International"
    },
    {
      "name": "Dallas Semiconductor / MAXIM"
    },
    {
      "name": "Dedicated Micros Ltd"
    },
    {
      "name": "DigiPATROL Ltd"
    },
    {
      "name": "Domo Limited"
    },
    {
      "name": "DVTel, Inc."
    },
    {
      "name": "ECIL"
    },
    {
      "name": "EGuardian International Co., Ltd"
    },
    {
      "name": "Elcom Door Comm (I) Pvt. Ltd."
    },
    {
      "name": "Elkosta Securities Systems India"
    },
    {
      "name": "Enterprise Software Solutions Lab"
    },
    {
      "name": "ET Srl"
    },
    {
      "name": "Etech Media Pvt. Ltd."
    },
    {
      "name": "FAAC India Pvt. Ltd."
    },
    {
      "name": "Falcon Alarms Systems Pvt Ltd"
    },
    {
      "name": "Fermax"
    },
    {
      "name": "Fire & Security Today"
    },
    {
      "name": "Fortuna Impex Pte. Ltd."
    },
    {
      "name": "Fujinon Singapore Pte Ltd"
    },
    {
      "name": "Fuqing Top Way Intelligent Science Technology Co.,"
    },
    {
      "name": "G3 Telebroadcast Convergence Pvt. Ltd."
    },
    {
      "name": "G4S Security Services (I) Pvt. Ltd."
    },
    {
      "name": "Gandhi Entrance Automations Pvt. Ltd."
    },
    {
      "name": "GE Security"
    },
    {
      "name": "Genius SpA"
    },
    {
      "name": "GIGA-TMS Inc"
    },
    {
      "name": "Godrej & Boyce Mfg. Co. Ltd"
    },
    {
      "name": "Golmar Sistemas de Communicacion, S.A"
    },
    {
      "name": "Grandeye Ltd"
    },
    {
      "name": "Hamilton Electronics P.Ltd."
    },
    {
      "name": "Hans India"
    },
    {
      "name": "Harcor Security Seals Pty Ltd"
    },
    {
      "name": "HashNine Managed Comm Ltd"
    },
    {
      "name": "Henan Hanwei Electronics Corp. Ltd"
    },
    {
      "name": "HID India Pvt. Ltd."
    },
    {
      "name": "Honeywell Security"
    },
    {
      "name": "Huper Laboratories Co. Ltd"
    },
    {
      "name": "I2 Limited"
    },
    {
      "name": "ICx Technologies"
    },
    {
      "name": "IJS Security"
    },
    {
      "name": "India SAFE"
    },
    {
      "name": "Indigovision"
    },
    {
      "name": "Innovative Energies"
    },
    {
      "name": "Iomniscient Pty Limited"
    },
    {
      "name": "J Mitra & Co."
    },
    {
      "name": "Kawach Protection Systems Pvt. Ltd."
    },
    {
      "name": "Keystone Electronics"
    },
    {
      "name": "KLA Systems Sdn Bhd."
    },
    {
      "name": "Kowa Co. Ltd."
    },
    {
      "name": "KSH International Co., Ltd."
    },
    {
      "name": "Lookman Electoplast Industries Ltd."
    },
    {
      "name": "M R Impex & Sons"
    },
    {
      "name": "Magnum"
    },
    {
      "name": "Mallcom (India) Limited"
    },
    {
      "name": "Mark Security Electronics Corporation"
    },
    {
      "name": "Mediatronix Pvt. Ltd."
    },
    {
      "name": "Move & Traffic Controls"
    },
    {
      "name": "N S Enterprises"
    },
    {
      "name": "Natchu Security Systems"
    },
    {
      "name": "Neotech Photoelectric Pvt. Ltd."
    },
    {
      "name": "Network Video Technologies,Inc."
    },
    {
      "name": "Nova ETS"
    },
    {
      "name": "Nova International"
    },
    {
      "name": "NVI Technologies Limited."
    },
    {
      "name": "Optex Co. Ltd."
    },
    {
      "name": "Optical Systems Design"
    },
    {
      "name": "OYTO Co Ltd"
    },
    {
      "name": "PANACOM TECHNOLOGY CORP."
    },
    {
      "name": "Panasonic Asia Pacific Pte. Ltd."
    },
    {
      "name": "Payne (India) Private Limited"
    },
    {
      "name": "PCI Limited"
    },
    {
      "name": "Peagasus Equipments Pvt. Ltd."
    },
    {
      "name": "Perpetuity Infotech India Pvt. Ltd."
    },
    {
      "name": "Prama Technologies"
    },
    {
      "name": "Precision Operations Systems (India) Pvt"
    },
    {
      "name": "Prolog Systems Limited"
    },
    {
      "name": "Qualitrade- Takex"
    },
    {
      "name": "Rajpurohi Cardtech Ltd."
    },
    {
      "name": "RBH Technologies India (P) Ltd."
    },
    {
      "name": "Rifatron Co., Ltd."
    },
    {
      "name": "Romtrac"
    },
    {
      "name": "Safety & Security Industry Program Office, MOEA ID"
    },
    {
      "name": "Sagem Defence Securite"
    },
    {
      "name": "Saima Sicurezza SpA"
    },
    {
      "name": "Sambson Watchnet"
    },
    {
      "name": "Samriddhi Automation"
    },
    {
      "name": "Sanyo India (P) Ltd."
    },
    {
      "name": "Seagate"
    },
    {
      "name": "Security Defense Systems"
    },
    {
      "name": "Security Dynamics"
    },
    {
      "name": "Security Today"
    },
    {
      "name": "Senstar-Stellar Corporation"
    },
    {
      "name": "SHENZHEN FUJIKAM INDUSTRY DEVELOPMENT CO. LTD"
    },
    {
      "name": "Siangsiu Industrial Corp"
    },
    {
      "name": "Siemens Building Technologies Pvt. Ltd."
    },
    {
      "name": "SJ Security systems Pvt. Ltd."
    },
    {
      "name": "SKJ Electronic Systems"
    },
    {
      "name": "Solutions Integrated Marketing Services"
    },
    {
      "name": "Sony Electronics (S) Pte. Ltd."
    },
    {
      "name": "Sony India Pvt. Ltd."
    },
    {
      "name": "SPACE inc"
    },
    {
      "name": "Spur Microwave Inc."
    },
    {
      "name": "STR International Inc"
    },
    {
      "name": "Syris Technology Corp."
    },
    {
      "name": "Systems Tek India Pvt. Ltd."
    },
    {
      "name": "Taiwan Electrical and Electronic Manufacturers' As"
    },
    {
      "name": "Taylor Lock Company Ltd"
    },
    {
      "name": "Technocrat Security Systems Pvt. Ltd."
    },
    {
      "name": "TeleEye Holdings Ltd."
    },
    {
      "name": "Thakral Services India Limited"
    },
    {
      "name": "TOMST s.r.o."
    },
    {
      "name": "Tradeindia.com"
    },
    {
      "name": "TRANS PACIFIC INDUSTRIES CORP."
    },
    {
      "name": "Tritech Security Systems Pvt. Ltd."
    },
    {
      "name": "Turbo Consultancy Services Pvt. Ltd."
    },
    {
      "name": "Tyche Peripheral Systems Ltd."
    },
    {
      "name": "Unishilp Electronics (P) Ltd."
    },
    {
      "name": "Univision Enterprises (Shenzhen) Co. Ltd"
    },
    {
      "name": "UWC Electric (M) Sdn Bhd."
    },
    {
      "name": "Vectra Security Solutions Pvt. Ltd."
    },
    {
      "name": "Vetrad Systems"
    },
    {
      "name": "Videcon Plc"
    },
    {
      "name": "Vista Security Technics Pvt. Ltd."
    },
    {
      "name": "WFE TECHNOLOGY CORP,"
    },
    {
      "name": "Z Plus Security Systems Pvt. Ltd."
    }
  ]
}

=== caatdata/arms-and-security-fair-exhibitors/data/ads-2016.json
{
  "name": "ADS 2016",
  "series": "ADS",
  "edition": "2016",
  "alias": [
    "ADS Show Europe 2016",
    "Aero Defence Support Show 2016",
    "World Military MRO Exhibition"
  ],
  "startDate": "2016-09-28",
  "endDate": "2016-09-29",
  "address": {
    "text": "Base Aérienne 106 - BORDEAUX MERIGNAC\n227 Avenue de l'Argonne\n33700 Mérignac\nFrance",
    "iso2": "FR",
    "lat": 44.8157029,
    "lon": -0.7092976999999999
  },
  "website": "http://www.adsshow.eu",
  "exhibitorListUrl": "http://www.adsshow.eu/fr/413-liste-des-partenaires.html",
  "social": {
    "platform": "twitter",
    "url": "https://twitter.com/ADSShow2016"
  }
}

=== caatdata/arms-and-security-fair-exhibitors/data/milipol-paris-2007.json
{
  "name": "Milipol Paris 2007",
  "series": "Milipol Paris",
  "edition": "2007",
  "startDate": "2007-10-09",
  "endDate": "2007-10-12",
  "address": {
    "text": "Paris Porte de Versailles\nPavilion 1\nParis\nFrance",
    "iso2": "FR",
    "lat": 48.8335509,
    "lon": 2.2841096
  },
  "website": "http://www.milipol.com",
  "organiser": [
    {
      "name": "EDS-MILIPOL",
      "address": "192, rue Legendre\n75017 Paris\nFrance"
    }
  ]
}
