=== caatdata/arms-and-security-fair-exhibitors/schema/fair.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Fair",
  "description": "A single arms and security fair, possibly including exhibitors and/or delegations.",
  "definitions": {
    "text": {
      "description": "A non-empty string.",
      "type": "string",
      "pattern": "^."
    },
    "textOrTextArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/text"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/text"
          }
        }
      ]
    },
    "url": {
      "$comment": "Poor source data will not pass even the simplest URL regex rule.",
      "type": "string"
    },
    "urlOrUrlArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/url"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/url"
          }
        }
      ]
    },
    "dateString": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
    },
    "dateStringPartial": {
      "type": "string",
      "pattern": "^[0-9]{4}(-[0-9]{2}){0,2}$"
    },
    "utcDatetimeString": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\+00:00$"
    },
    "iso2": {
      "type": "string",
      "pattern": "^[A-Z]{2}$"
    },
    "address": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "iso2": {
              "$ref": "#/definitions/iso2"
            },
            "lat": {
              "type": "number",
              "minimum": -90,
              "maximum": 90
            },
            "lon": {
              "type": "number",
              "minimum": -180,
              "maximum": 180
            }
          },
          "required": [
            "text",
            "iso2",
            "lat",
            "lon"
          ],
          "additionalProperties": false
        }
      ]
    },
    "addressOrAddressArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/address"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/address"
          }
        }
      ]
    },
    "country": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "iso2": {
              "$ref": "#/definitions/iso2"
            }
          },
          "required": [
            "text",
            "iso2"
          ],
          "additionalProperties": false
        }
      ]
    },
    "countryOrCountryArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/country"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/country"
          }
        }
      ]
    },
    "social": {
      "type": "object",
      "oneOf": [
        {
          "required": [
            "platform",
            "handle"
          ]
        },
        {
          "required": [
            "platform",
            "url"
          ]
        }
      ],
      "properties": {
        "platform": {
          "$ref": "#/definitions/text"
        },
        "handle": {
          "$ref": "#/definitions/text"
        },
        "url": {
          "$ref": "#/definitions/text"
        }
      }
    },
    "socialOrSocialArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/social"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/social"
          }
        }
      ]
    },
    "exhibitor": {
      "type": "object",
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "$ref": "#/definitions/text"
        },
        "alias": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "exhibitorUrl": {
          "$ref": "#/definitions/url"
        },
        "address": {
          "$ref": "#/definitions/addressOrAddressArray"
        },
        "country": {
          "$ref": "#/definitions/countryOrCountryArray"
        },
        "website": {
          "$ref": "#/definitions/urlOrUrlArray"
        },
        "email": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "telephone": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "social": {
          "$ref": "#/definitions/socialOrSocialArray"
        },
        "category": {
          "$ref": "#/definitions/textOrTextArray"
        }
      }
    },
    "organiser": {
      "type": "object",
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "$ref": "#/definitions/text"
        },
        "alias": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "address": {
          "$ref": "#/definitions/addressOrAddressArray"
        },
        "country": {
          "$ref": "#/definitions/countryOrCountryArray"
        },
        "website": {
          "$ref": "#/definitions/urlOrUrlArray"
        },
        "email": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "telephone": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "social": {
          "$ref": "#/definitions/socialOrSocialArray"
        }
      }
    }
  },
  "type": "object",
  "required": [
    "name"
  ],
  "oneOf": [
    {
      "required": [
        "startDate",
        "endDate"
      ]
    },
    {
      "required": [
        "approxDate"
      ]
    }
  ],
  "dependencies": {
    "exhibitor": [
      "exhibitorListDate"
    ],
    "delegation": [
      "delegationListDate"
    ]
  },
  "additionalProperties": false,
  "properties": {
    "name": {
      "$ref": "#/definitions/text"
    },
    "alias": {
      "$ref": "#/definitions/textOrTextArray"
    },
    "series": {
      "$ref": "#/definitions/text"
    },
    "edition": {
      "$ref": "#/definitions/text"
    },
    "startDate": {
      "$ref": "#/definitions/dateString"
    },
    "endDate": {
      "$ref": "#/definitions/dateString"
    },
    "approxDate": {
      "$ref": "#/definitions/dateStringPartial"
    },
    "address": {
      "$ref": "#/definitions/addressOrAddressArray"
    },
    "country": {
      "$ref": "#/definitions/countryOrCountryArray"
    },
    "online": {
      "type": "boolean"
    },
    "website": {
      "$ref": "#/definitions/urlOrUrlArray"
    },
    "social": {
      "$ref": "#/definitions/socialOrSocialArray"
    },
    "organiser": {
      "anyOf": [
        {
          "$ref": "#/definitions/organiser"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/organiser"
          }
        }
      ]
    },
    "exhibitorListUrl": {
      "$ref": "#/definitions/url"
    },
    "exhibitorListDate": {
      "$ref": "#/definitions/utcDatetimeString"
    },
    "exhibitor": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/exhibitor"
      }
    },
    "exhibitorListIncomplete": {
      "type": "boolean",
      "const": true
    },
    "delegationListUrl": {
      "$ref": "#/definitions/url"
    },
    "delegationListDate": {
      "$ref": "#/definitions/utcDatetimeString"
    },
    "delegation": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "$ref": "#/definitions/text"
          },
          "attended": {
            "type": "boolean"
          },
          "retracted": {
            "type": "boolean"
          }
        }
      }
    }
  }
}

=== caatdata/arms-and-security-fair-exhibitors/data/iavs-2013.json
{
  "name": "IAVs 2013",
  "series": "IAVs",
  "edition": "2013",
  "alias": "International Armoured Vehicles 2013",
  "startDate": "2013-02-05",
  "endDate": "2013-02-08",
  "address": {
    "text": "FIVE\nFarnborough\nUK",
    "iso2": "GB",
    "lat": 51.2753235,
    "lon": -0.7665162999999999
  },
  "website": [
    "http://www.internationalarmouredvehicles.com",
    "http://internationalarmouredvehicles.wordpress.com"
  ],
  "social": [
    {
      "platform": "twitter",
      "url": "http://twitter.com/IAVehicles"
    },
    {
      "platform": "linkedin",
      "url": "http://www.linkedin.com/groupRegistration?gid=162026"
    },
    {
      "platform": "facebook",
      "url": "http://www.facebook.com/pages/London-United-Kingdom/International-Armoured-Vehicles/104213052965477"
    }
  ],
  "organiser": [
    {
      "name": "IQPC",
      "website": "http://www.iqpc.com"
    },
    {
      "name": "Defence IQ",
      "website": "http://www.defenceiq.com"
    }
  ],
  "exhibitorListUrl": "http://www.internationalarmouredvehicles.com/Event.aspx?id=734202",
  "exhibitorListDate": "2022-02-02T16:32:38+00:00",
  "exhibitor": [
    {
      "name": "Ares Security Vehicles"
    },
    {
      "name": "ArmourWorks International Ltd"
    },
    {
      "name": "Barco NV"
    },
    {
      "name": "Brimar Ltd."
    },
    {
      "name": "Constellium"
    },
    {
      "name": "FFG Flensburger Fahrzeugbau Gesellschaft mbH"
    },
    {
      "name": "GoodWolfe Energy"
    },
    {
      "name": "GuS GmbH & Co. KG"
    },
    {
      "name": "Hutchinson Defence"
    },
    {
      "name": "ITT Corporation"
    },
    {
      "name": "Igus (UK) Ltd"
    },
    {
      "name": "International Armored Group, (IAG)"
    },
    {
      "name": "Iveco Defence Vehicles"
    },
    {
      "name": "JCB Government and Defence"
    },
    {
      "name": "KTK"
    },
    {
      "name": "Kaller Str√∂msholmen AB"
    },
    {
      "name": "Kembrey Wiring Systems Ltd"
    },
    {
      "name": "Kent Modular Electronics Limited (KME)"
    },
    {
      "name": "Lorica Systems"
    },
    {
      "name": "MJ Services aka ThermBright"
    },
    {
      "name": "PPG Aerospace"
    },
    {
      "name": "Polamco Ltd."
    },
    {
      "name": "Proengin"
    },
    {
      "name": "RUAG Defence"
    },
    {
      "name": "Renault Trucks Defense"
    },
    {
      "name": "Respirator"
    },
    {
      "name": "Rheinmetall Chempro GmbH"
    },
    {
      "name": "SCHOTT AG"
    },
    {
      "name": "SCHROTH Safety Products GmbH"
    },
    {
      "name": "Saab Barracuda"
    },
    {
      "name": "Scanfiber Composites UK Ltd"
    },
    {
      "name": "Shield Technologies"
    },
    {
      "name": "Sika"
    },
    {
      "name": "Sil-Mid"
    },
    {
      "name": "SpanSet"
    },
    {
      "name": "Stream Enviro"
    },
    {
      "name": "Streit Group"
    },
    {
      "name": "Systematic"
    },
    {
      "name": "Timoney Technology Ltd"
    },
    {
      "name": "Transhield"
    },
    {
      "name": "Tyron Developments Ltd"
    },
    {
      "name": "Universal Engineering Group (UN)"
    },
    {
      "name": "ViaSat, Inc"
    },
    {
      "name": "Vitavox"
    },
    {
      "name": "WARN INDUSTRIES"
    },
    {
      "name": "Yugoimport"
    }
  ]
}

=== caatdata/arms-and-security-fair-exhibitors/data/ifsec-bangladesh-2019.json
{
  "name": "IFSEC Bangladesh 2019",
  "series": "IFSEC Bangladesh",
  "edition": "2019",
  "alias": [
    "International Fire Security Exhibition and Conference Bangladesh"
  ],
  "startDate": "2019-04-18",
  "endDate": "2019-04-20",
  "address": "ICCB\nDhaka\nBangladesh",
  "website": "https://www.ifsec.events/bangladesh/",
  "organiser": [
    {
      "name": "UBM India"
    },
    {
      "name": "Informa Markets",
      "website": "https://www.informamarkets.com/"
    }
  ]
}

=== caatdata/arms-and-security-fair-exhibitors/data/international-military-helicopter-2024.json
{
  "name": "International Military Helicopter 2024",
  "series": "International Military Helicopter",
  "edition": "2024",
  "startDate": "2024-02-27",
  "endDate": "2024-02-29",
  "address": {
    "text": "Twickenham Stadium\n200 Whitton Rd\nTwickenham\nTW2 7BA\nUnited Kingdom",
    "iso2": "GB",
    "lat": 51.4559558,
    "lon": -0.3415051
  },
  "website": "https://www.defenceiq.com/events-militaryhelicopter",
  "organiser": [
    {
      "name": "Defence IQ",
      "website": "http://www.defenceiq.com"
    },
    {
      "name": "Institute for Defense and Government Advancement",
      "alias": "IDGA",
      "website": "https://www.idga.org/"
    }
  ],
  "exhibitorListUrl": "https://www.defenceiq.com/events-militaryhelicopter/sponsors",
  "exhibitorListDate": "2024-04-10T09:05:37+00:00",
  "exhibitor": [
    {
      "name": "ARKA",
      "website": "arka.org"
    },
    {
      "name": "Airbus"
    },
    {
      "name": "Ascent",
      "website": "ascentflighttraining.com"
    },
    {
      "name": "Bell",
      "website": "www.bellflight.com"
    },
    {
      "name": "Boeing",
      "website": "www.boeing.com"
    },
    {
      "name": "Chelton",
      "website": "chelton.com"
    },
    {
      "name": "Collins Aerospace",
      "website": "collinsaerospace.com"
    },
    {
      "name": "DA Group",
      "website": "www.da-group.com"
    },
    {
      "name": "FlySight",
      "website": "www.flysight.it"
    },
    {
      "name": "GE Aerospace",
      "website": "www.geaerospace.com"
    },
    {
      "name": "GTA Containers",
      "website": "www.gtacontainers.com"
    },
    {
      "name": "Hensoldt",
      "website": "https://www.hensoldt.net"
    },
    {
      "name": "HoodTech Vision",
      "website": "hoodtechvision.com"
    },
    {
      "name": "Leonardo"
    },
    {
      "name": "MD Helicopter",
      "website": "mdhelicopters.com"
    },
    {
      "name": "Marvin Test Solutions",
      "website": "www.marvintest.com"
    },
    {
      "name": "NHIndustries",
      "website": "www.nhindustries.com"
    },
    {
      "name": "Nova Systems",
      "website": "www.novasystems.com"
    },
    {
      "name": "Sikorsky"
    },
    {
      "name": "Snap-on Industrial",
      "website": "snapon-industrial.co.uk"
    },
    {
      "name": "Thales",
      "website": "www.thalesgroup.com"
    }
  ]
}

=== caatdata/arms-and-security-fair-exhibitors/data/dimdex-2022.json
{
  "name": "DIMDEX 2022",
  "series": "DIMDEX",
  "edition": "2022",
  "alias": "Doha International Maritime Defence Exhibition and Conference 2022",
  "startDate": "2022-03-21",
  "endDate": "2022-03-23",
  "address": "Qatar National Convention Centre (QNCC)\nDoha\nQatar",
  "website": "http://www.dimdex.com",
  "social": [
    {
      "platform": "facebook",
      "url": "https://www.facebook.com/dimdexqatar/"
    },
    {
      "platform": "twitter",
      "url": "https://twitter.com/DIMDEXQatar"
    },
    {
      "platform": "youtube",
      "url": "https://www.youtube.com/channel/UCpHS5Sf4nFhSAMRm2CTe5Vg/videos"
    }
  ],
  "organiser": [
    {
      "name": "Qatar Armed Forces"
    }
  ],
  "delegationListUrl": "https://dimdex.com/vip-delegations/",
  "delegationListDate": "2022-02-09T16:26:43+00:00",
  "delegation": [
    {
      "name": "ALGERIA"
    },
    {
      "name": "ARGENTINA"
    },
    {
      "name": "AUSTRALIA"
    },
    {
      "name": "AUSTRIA"
    },
    {
      "name": "AZERBAIJAN"
    },
    {
      "name": "BANGLADESH"
    },
    {
      "name": "BELARUS"
    },
    {
      "name": "BELGIUM"
    },
    {
      "name": "BOSNIA AND HERZEGOVINA"
    },
    {
      "name": "BRAZIL"
    },
    {
      "name": "THE BRUNEI DARUSSALAM"
    },
    {
      "name": "BULGARIA"
    },
    {
      "name": "BURKINA FASO"
    },
    {
      "name": "KINGDOM OF CAMBODIA"
    },
    {
      "name": "CAMEROON"
    },
    {
      "name": "CANADA"
    },
    {
      "name": "CHAD"
    },
    {
      "name": "CHILE"
    },
    {
      "name": "CHINA"
    },
    {
      "name": "COLOMBIA"
    },
    {
      "name": "CROATIA"
    },
    {
      "name": "DENMARK"
    },
    {
      "name": "DJIBOUTI"
    },
    {
      "name": "DOMINICAN REPUBLIC"
    },
    {
      "name": "ECUADOR"
    },
    {
      "name": "EGYPT"
    },
    {
      "name": "ERITREA"
    },
    {
      "name": "ETHIOPIA"
    },
    {
      "name": "FINLAND"
    },
    {
      "name": "FRANCE"
    },
    {
      "name": "GERMANY"
    },
    {
      "name": "GHANA"
    },
    {
      "name": "GREECE"
    },
    {
      "name": "GUINEA"
    },
    {
      "name": "INDIA"
    },
    {
      "name": "INDONESIA"
    },
    {
      "name": "IRAQ"
    },
    {
      "name": "IRELAND"
    },
    {
      "name": "ITALY"
    },
    {
      "name": "IVORY COAST"
    },
    {
      "name": "JAPAN"
    },
    {
      "name": "JORDAN"
    },
    {
      "name": "KAZAKHSTAN"
    },
    {
      "name": "KENYA"
    },
    {
      "name": "KUWAIT"
    },
    {
      "name": "LEBANON"
    },
    {
      "name": "MALAYSIA"
    },
    {
      "name": "MALI"
    },
    {
      "name": "MALTA"
    },
    {
      "name": "MEXICO"
    },
    {
      "name": "MONGOLIA"
    },
    {
      "name": "KINGDOM OF MOROCCO"
    },
    {
      "name": "NATO"
    },
    {
      "name": "NETHERLANDS"
    },
    {
      "name": "NIGER"
    },
    {
      "name": "NIGERIA"
    },
    {
      "name": "NORWAY"
    },
    {
      "name": "OMAN"
    },
    {
      "name": "ISLAMIC REPUBLIC OF PAKISTAN"
    },
    {
      "name": "PERU"
    },
    {
      "name": "PHILIPPINES"
    },
    {
      "name": "POLAND"
    },
    {
      "name": "ROMANIA"
    },
    {
      "name": "RUSSIA"
    },
    {
      "name": "RWANDA"
    },
    {
      "name": "SENEGAL"
    },
    {
      "name": "SINGAPORE"
    },
    {
      "name": "SOMALIA"
    },
    {
      "name": "SOUTH AFRICA"
    },
    {
      "name": "SOUTH KOREA"
    },
    {
      "name": "SPAIN"
    },
    {
      "name": "SRI LANKA"
    },
    {
      "name": "SUDAN"
    },
    {
      "name": "SWEDEN"
    },
    {
      "name": "TANZANIA"
    },
    {
      "name": "KINGDOM OF THAILAND"
    },
    {
      "name": "TUNISIA"
    },
    {
      "name": "TÃœRKIYE"
    },
    {
      "name": "UGANDA"
    },
    {
      "name": "UKRAINE"
    },
    {
      "name": "UNITED KINGDOM"
    },
    {
      "name": "UNITED STATES OF AMERICA"
    },
    {
      "name": "VENEZUELA"
    }
  ]
}

=== caatdata/arms-and-security-fair-exhibitors/data/iavs-2018.json
{
  "name": "IAVs 2018",
  "series": "IAVs",
  "edition": "2018",
  "alias": "International Armoured Vehicles 2018",
  "startDate": "2018-01-22",
  "endDate": "2018-01-25",
  "address": "Twickenham Stadium\n200 Whitton Road Twickenham\nLondon TW2 7BA\nUnited Kingdom",
  "website": "http://www.internationalarmouredvehicles.com",
  "social": [
    {
      "platform": "twitter",
      "url": "http://twitter.com/IAVehicles"
    },
    {
      "platform": "linkedin",
      "url": "https://www.linkedin.com/groups/162026"
    },
    {
      "platform": "facebook",
      "url": "https://www.facebook.com/DefenceIQNetwork/"
    }
  ],
  "organiser": [
    {
      "name": "IQPC",
      "website": "http://www.iqpc.com"
    },
    {
      "name": "Defence IQ",
      "website": "http://www.defenceiq.com",
      "social": [
        {
          "platform": "youtube",
          "url": "https://www.youtube.com/user/TheDefenceIQ"
        }
      ]
    }
  ],
  "exhibitorListUrl": "https://www.internationalarmouredvehicles.com/sponsors",
  "exhibitorListDate": "2021-03-11T13:33:03+00:00",
  "exhibitor": [
    {
      "name": "NIMR",
      "website": "http://www.nimr.ae"
    },
    {
      "name": "BAE Systems",
      "website": "http://www.baesystems.com"
    },
    {
      "name": "General Dynamics Land Systems",
      "website": "http://gdls.com/"
    },
    {
      "name": "Nexter",
      "website": "http://www.nexter-group.com"
    },
    {
      "name": "Patria",
      "website": "http://www.patria.fi"
    },
    {
      "name": "Rheinmetall Defence",
      "website": "http://www.rheinmetall-defence.com/"
    },
    {
      "name": "RUAG Defence",
      "website": "http://www.ruag.com"
    },
    {
      "name": "Leonardo",
      "website": "http://www.leonardocompany.com/en"
    },
    {
      "name": "Lockheed Martin",
      "website": "http://www.lockheedmartin.com"
    },
    {
      "name": "Thales",
      "website": "http://www.thalesgroup.com"
    },
    {
      "name": "CMI Defence",
      "website": "http://www.cmigroupe.com/en/p/sector-defence"
    },
    {
      "name": "FFG",
      "website": "http://www.ffg-flensburg.de/en/home/"
    },
    {
      "name": "Morgan Advanced Materials",
      "website": "http://www.morganadvancedmaterials.com/"
    },
    {
      "name": "Rafael Advanced Defense Systems Ltd.",
      "website": "http://www.rafael.co.il/Marketing/203-en/Marketing.aspx"
    },
    {
      "name": "Raytheon",
      "website": "http://www.raytheon.com"
    },
    {
      "name": "Revision Military",
      "website": "https://www.revisionmilitary.com/"
    },
    {
      "name": "Soucy Defense",
      "website": "http://www.soucy-defense.com/home"
    },
    {
      "name": "Texelis",
      "website": "http://www.texelis.com"
    },
    {
      "name": "ADS (Active Defence Systems)",
      "website": "http://www.ads-protection.org/"
    },
    {
      "name": "Allison Transmission",
      "website": "http://www.allisontransmission.com/"
    },
    {
      "name": "American Panel Corporation",
      "website": "http://american-panel.com/"
    },
    {
      "name": "Amphenol",
      "website": "http://www.amphenolmao.com"
    },
    {
      "name": "ARTEC GmbH",
      "website": "http://artec-boxer.com/"
    },
    {
      "name": "EnerSys",
      "website": "http://www.enersys.com/GlobalLanding.aspx"
    },
    {
      "name": "Esterline | Control & Communication Systems",
      "website": "http://www.esterline.com"
    },
    {
      "name": "Metravib",
      "website": "http://metravib.acoemgroup.com/"
    },
    {
      "name": "Milspec",
      "website": "http://milspecmanufacturing.com/"
    },
    {
      "name": "NLMK Clabecq",
      "website": "http://quardian.me/"
    },
    {
      "name": "Palomar Display Products, Inc.",
      "website": "http://www.palomardisplays.com/"
    },
    {
      "name": "TII Group",
      "website": "https://www.tii-group.com/"
    },
    {
      "name": "Ultra PALS",
      "website": "http://www.ultra-pals.com/"
    },
    {
      "name": "UTC Aerospace Systems",
      "website": "http://www.utcaerospacesystems.com"
    },
    {
      "name": "AmSafe Bridport",
      "website": "http://www.amsafebridport.com"
    },
    {
      "name": "Bren Tronics",
      "website": "https://www.bren-tronics.com/"
    },
    {
      "name": "Caterpillar Defence Products",
      "website": "http://www.cat.com/en_GB/products/new/by-industry/governmental-defense.html"
    },
    {
      "name": "FN Herstal",
      "website": "http://www.fnherstal.com/"
    },
    {
      "name": "ITT Corporation",
      "website": "http://www.itt.com/Home/"
    },
    {
      "name": "Jankel",
      "website": "http://www.jankel.com/"
    },
    {
      "name": "Kent Modular Electronics",
      "website": "http://www.kme.co.uk/"
    },
    {
      "name": "Michelin Tires",
      "website": "http://www.michelin.ie/"
    },
    {
      "name": "Microflown AVISA",
      "website": "http://www.microflown-avisa.com"
    },
    {
      "name": "NBC-Sys",
      "website": "http://www.nexter-group.fr/en/subsidiaries/nbc-sys"
    },
    {
      "name": "Pearson Engineering",
      "website": "http://www.pearson-eng.com/"
    },
    {
      "name": "Proengin",
      "website": "http://www.proengin.com/"
    },
    {
      "name": "QinetiQ",
      "website": "http://www.qinetiq.com"
    },
    {
      "name": "Radnor",
      "website": "http://radnor.org.uk/"
    },
    {
      "name": "Scepter Canada",
      "website": "http://mil.sceptermilitary.com/"
    },
    {
      "name": "TenCate Advanced Armour",
      "website": "http://www.tencate.com"
    },
    {
      "name": "Timoney Technology",
      "website": "http://timoneygroup.com/Index.aspx"
    },
    {
      "name": "Tyron Runflat Ltd",
      "website": "http://www.tyron.com"
    },
    {
      "name": "Vitec",
      "website": "https://www.vitec.com/"
    },
    {
      "name": "Beth-El Zikhron Yaaqov Industries Ltd.",
      "website": "http://www.beind.com/"
    },
    {
      "name": "FNSS - Savunma Sistemleri A.S.",
      "website": "http://www.fnss.com.tr"
    },
    {
      "name": "IBD Deisenroth Engineering",
      "website": "http://www.ibd-deisenroth-engineering.de/"
    },
    {
      "name": "Saab",
      "website": "http://saab.com/"
    },
    {
      "name": "Newton Europe",
      "website": "http://www.newtoneurope.com"
    }
  ]
}

=== caatdata/arms-and-security-fair-exhibitors/data/aoc-europe-2018.json
{
  "name": "AOC Europe 2018",
  "series": "AOC Europe",
  "edition": "2018",
  "alias": [
    "Association of Old Crows 2018",
    "Electronic Warfare Europe 2018",
    "EW Europe 2018"
  ],
  "startDate": "2018-06-05",
  "endDate": "2018-06-07",
  "address": {
    "text": "Congr√®s Beaulieu\nLausanne\nSwitzerland",
    "iso2": "CH",
    "lat": 46.5287017,
    "lon": 6.6259245
  },
  "website": "https://www.eweurope.com",
  "organiser": {
    "name": "Clarion Defence & Security"
  }
}
