=== caatdata/arms-and-security-fair-exhibitors/schema/fair.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Fair",
  "description": "A single arms and security fair, possibly including exhibitors and/or delegations.",
  "definitions": {
    "text": {
      "description": "A non-empty string.",
      "type": "string",
      "pattern": "^."
    },
    "textOrTextArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/text"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/text"
          }
        }
      ]
    },
    "url": {
      "$comment": "Poor source data will not pass even the simplest URL regex rule.",
      "type": "string"
    },
    "urlOrUrlArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/url"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/url"
          }
        }
      ]
    },
    "dateString": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
    },
    "dateStringPartial": {
      "type": "string",
      "pattern": "^[0-9]{4}(-[0-9]{2}){0,2}$"
    },
    "utcDatetimeString": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\+00:00$"
    },
    "iso2": {
      "type": "string",
      "pattern": "^[A-Z]{2}$"
    },
    "address": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "iso2": {
              "$ref": "#/definitions/iso2"
            },
            "lat": {
              "type": "number",
              "minimum": -90,
              "maximum": 90
            },
            "lon": {
              "type": "number",
              "minimum": -180,
              "maximum": 180
            }
          },
          "required": [
            "text",
            "iso2",
            "lat",
            "lon"
          ],
          "additionalProperties": false
        }
      ]
    },
    "addressOrAddressArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/address"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/address"
          }
        }
      ]
    },
    "country": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "iso2": {
              "$ref": "#/definitions/iso2"
            }
          },
          "required": [
            "text",
            "iso2"
          ],
          "additionalProperties": false
        }
      ]
    },
    "countryOrCountryArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/country"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/country"
          }
        }
      ]
    },
    "social": {
      "type": "object",
      "oneOf": [
        {
          "required": [
            "platform",
            "handle"
          ]
        },
        {
          "required": [
            "platform",
            "url"
          ]
        }
      ],
      "properties": {
        "platform": {
          "$ref": "#/definitions/text"
        },
        "handle": {
          "$ref": "#/definitions/text"
        },
        "url": {
          "$ref": "#/definitions/text"
        }
      }
    },
    "socialOrSocialArray": {
      "anyOf": [
        {
          "$ref": "#/definitions/social"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/social"
          }
        }
      ]
    },
    "exhibitor": {
      "type": "object",
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "$ref": "#/definitions/text"
        },
        "alias": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "exhibitorUrl": {
          "$ref": "#/definitions/url"
        },
        "address": {
          "$ref": "#/definitions/addressOrAddressArray"
        },
        "country": {
          "$ref": "#/definitions/countryOrCountryArray"
        },
        "website": {
          "$ref": "#/definitions/urlOrUrlArray"
        },
        "email": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "telephone": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "social": {
          "$ref": "#/definitions/socialOrSocialArray"
        },
        "category": {
          "$ref": "#/definitions/textOrTextArray"
        }
      }
    },
    "organiser": {
      "type": "object",
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "$ref": "#/definitions/text"
        },
        "alias": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "address": {
          "$ref": "#/definitions/addressOrAddressArray"
        },
        "country": {
          "$ref": "#/definitions/countryOrCountryArray"
        },
        "website": {
          "$ref": "#/definitions/urlOrUrlArray"
        },
        "email": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "telephone": {
          "$ref": "#/definitions/textOrTextArray"
        },
        "social": {
          "$ref": "#/definitions/socialOrSocialArray"
        }
      }
    }
  },
  "type": "object",
  "required": [
    "name"
  ],
  "oneOf": [
    {
      "required": [
        "startDate",
        "endDate"
      ]
    },
    {
      "required": [
        "approxDate"
      ]
    }
  ],
  "dependencies": {
    "exhibitor": [
      "exhibitorListDate"
    ],
    "delegation": [
      "delegationListDate"
    ]
  },
  "additionalProperties": false,
  "properties": {
    "name": {
      "$ref": "#/definitions/text"
    },
    "alias": {
      "$ref": "#/definitions/textOrTextArray"
    },
    "series": {
      "$ref": "#/definitions/text"
    },
    "edition": {
      "$ref": "#/definitions/text"
    },
    "startDate": {
      "$ref": "#/definitions/dateString"
    },
    "endDate": {
      "$ref": "#/definitions/dateString"
    },
    "approxDate": {
      "$ref": "#/definitions/dateStringPartial"
    },
    "address": {
      "$ref": "#/definitions/addressOrAddressArray"
    },
    "country": {
      "$ref": "#/definitions/countryOrCountryArray"
    },
    "online": {
      "type": "boolean"
    },
    "website": {
      "$ref": "#/definitions/urlOrUrlArray"
    },
    "social": {
      "$ref": "#/definitions/socialOrSocialArray"
    },
    "organiser": {
      "anyOf": [
        {
          "$ref": "#/definitions/organiser"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/organiser"
          }
        }
      ]
    },
    "exhibitorListUrl": {
      "$ref": "#/definitions/url"
    },
    "exhibitorListDate": {
      "$ref": "#/definitions/utcDatetimeString"
    },
    "exhibitor": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/exhibitor"
      }
    },
    "exhibitorListIncomplete": {
      "type": "boolean",
      "const": true
    },
    "delegationListUrl": {
      "$ref": "#/definitions/url"
    },
    "delegationListDate": {
      "$ref": "#/definitions/utcDatetimeString"
    },
    "delegation": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "$ref": "#/definitions/text"
          },
          "attended": {
            "type": "boolean"
          },
          "retracted": {
            "type": "boolean"
          }
        }
      }
    }
  }
}

=== caatdata/arms-and-security-fair-exhibitors/data/mspo-2025.json
{
  "name": "MSPO 2025",
  "series": "MSPO",
  "edition": "2025",
  "alias": [
    "33rd International Defence Industry Exhibition MSPO",
    "Międzynarodowy Salon Przemysłu Obronnego"
  ],
  "startDate": "2025-09-02",
  "endDate": "2025-09-05",
  "address": {
    "text": "Targi Kielce\nSt. Zakładowa 1\n25-672 Kielce\nPoland",
    "iso2": "PL",
    "lat": 50.8989729,
    "lon": 20.5885514
  },
  "website": "https://www.targikielce.pl/en/mspo",
  "organiser": {
    "name": "Targi Kielce",
    "address": "Targi Kielce\nSt. Zakładowa 1\n25-672 Kielce\nPoland",
    "website": "https://www.targikielce.pl",
    "social": [
      {
        "platform": "facebook",
        "url": "https://www.facebook.com/targikielce"
      },
      {
        "platform": "twitter",
        "url": "https://twitter.com/targikielce"
      },
      {
        "platform": "instagram",
        "url": "https://www.instagram.com/targikielce/"
      },
      {
        "platform": "youtube",
        "url": "https://www.youtube.com/user/TargiKielce1"
      },
      {
        "platform": "linkedin",
        "url": "https://www.linkedin.com/company/targi-kielce-sa"
      }
    ]
  }
}

=== caatdata/arms-and-security-fair-exhibitors/data/cansec-2014.json
{
  "name": "CANSEC 2014",
  "series": "CANSEC",
  "edition": "2014",
  "startDate": "2014-05-28",
  "endDate": "2014-05-29",
  "address": {
    "text": "EY Centre\nOttawa\nOntario\nCanada",
    "iso2": "CA",
    "lat": 45.3322655,
    "lon": -75.653978
  },
  "website": "https://www.defenceandsecurity.ca/CANSEC/",
  "organiser": [
    {
      "name": "CADSI",
      "alias": "Canadian Association of Defence and Security Industries",
      "website": "https://www.defenceandsecurity.ca/"
    }
  ]
}

=== caatdata/arms-and-security-fair-exhibitors/data/ifsec-india-2007.json
{
  "name": "IFSEC India 2007",
  "series": "IFSEC India",
  "edition": "2007",
  "alias": [
    "Internal Security India",
    "Counter Terror India Conference"
  ],
  "startDate": "2007-10-25",
  "endDate": "2007-10-27",
  "address": "Pragati Maidan\nNew Delhi\nIndia",
  "website": "http://www.ifsecindia.com/",
  "organiser": [
    {
      "name": "CMP Information",
      "website": "http://www.cmpi.biz"
    },
    {
      "name": "UBM India",
      "website": "http://www.ubmindia.in/"
    }
  ],
  "exhibitorListUrl": "http://www.ifsecindia.com/page.cfm?&LinkType=PowerBar__&LinkTarget=http://www.ifsecindia.com/page.cfm/Action=ExhibList/t=m",
  "exhibitorListDate": "2022-03-10T21:38:00+00:00",
  "exhibitor": [
    {
      "name": "A & S Group"
    },
    {
      "name": "A V Systems"
    },
    {
      "name": "Access Dynamics"
    },
    {
      "name": "ACTAtek Ltd"
    },
    {
      "name": "Adept Designs"
    },
    {
      "name": "Adion Technologies Pvt. Ltd."
    },
    {
      "name": "Adit Enterprise"
    },
    {
      "name": "Aditya Infotech Ltd."
    },
    {
      "name": "Adtech Systems Limited"
    },
    {
      "name": "Advanced Detection Technology"
    },
    {
      "name": "Advert Technologies"
    },
    {
      "name": "Al Waheed General Trading Co. (GBP)"
    },
    {
      "name": "Alba Control Systems Ltd."
    },
    {
      "name": "Alba Urmet Comm & Security (P) Ltd."
    },
    {
      "name": "All e Technologies (P) Ltd."
    },
    {
      "name": "AMG Systems"
    },
    {
      "name": "Amron Associates Private Ltd."
    },
    {
      "name": "Aravli Hitech"
    },
    {
      "name": "Arise Security Systems"
    },
    {
      "name": "Arya Communications & Electronics Pvt. L"
    },
    {
      "name": "Arya Communications & Electronics Services Pvt. Ltd"
    },
    {
      "name": "Asia Info Company Ltd"
    },
    {
      "name": "Asian Professional Security Association"
    },
    {
      "name": "Astraguard Pvt. Ltd"
    },
    {
      "name": "Autocop Security Solutions Pvt. Ltd."
    },
    {
      "name": "Axis Communication"
    },
    {
      "name": "AXVIEW TECHNOLOGY (SHENZHEN) CO., LTD"
    },
    {
      "name": "AXXON"
    },
    {
      "name": "BFT S.P.A."
    },
    {
      "name": "Bioinsec Co., Ltd"
    },
    {
      "name": "Bitron Video SRL"
    },
    {
      "name": "Biztradeshows.com"
    },
    {
      "name": "Bluecard Software Technology Co Ltd"
    },
    {
      "name": "CBC Co. Ltd."
    },
    {
      "name": "CDVI"
    },
    {
      "name": "China Public Security"
    },
    {
      "name": "Chubb Alba Control Systems Ltd."
    },
    {
      "name": "CIEFFE S.p.A"
    },
    {
      "name": "Comm Port Technologies Inc."
    },
    {
      "name": "Computer Recognition Systems"
    },
    {
      "name": "COP SECURITY SYSTEM CORP."
    },
    {
      "name": "Cradle Technologies India Pvt. Ltd."
    },
    {
      "name": "Crockett International"
    },
    {
      "name": "Dallas Semiconductor / MAXIM"
    },
    {
      "name": "Dedicated Micros Ltd"
    },
    {
      "name": "DigiPATROL Ltd"
    },
    {
      "name": "Domo Limited"
    },
    {
      "name": "DVTel Inc."
    },
    {
      "name": "DVTel, Inc."
    },
    {
      "name": "Eastland Business Corporation"
    },
    {
      "name": "ECIL"
    },
    {
      "name": "EGuardian International Co., Ltd"
    },
    {
      "name": "Elcom Door Comm (I) Pvt. Ltd."
    },
    {
      "name": "Elkosta Securities Systems India"
    },
    {
      "name": "Enterprise Software Solutions Lab"
    },
    {
      "name": "ET Srl"
    },
    {
      "name": "FAAC India Pvt. Ltd."
    },
    {
      "name": "Falcon Alarms Systems Pvt Ltd"
    },
    {
      "name": "Falcon Alarms Systems Pvt. Ltd"
    },
    {
      "name": "Falcontrol"
    },
    {
      "name": "Fermax"
    },
    {
      "name": "Fire & Security Today"
    },
    {
      "name": "Fortuna Impex Pte. Ltd."
    },
    {
      "name": "Fujinon Singapore Pte Ltd"
    },
    {
      "name": "Fuqing Top Way Intelligent Science Technology Co., Ltd"
    },
    {
      "name": "G3 Telebroadcast Convergence Pvt. Ltd."
    },
    {
      "name": "G4S Security Services (I) Pvt. Ltd."
    },
    {
      "name": "Gandhi Entrance Automations Pvt. Ltd."
    },
    {
      "name": "GE Security"
    },
    {
      "name": "Genius SpA"
    },
    {
      "name": "GIGA-TMS Inc"
    },
    {
      "name": "Godrej & Boyce Mfg. Co. Ltd"
    },
    {
      "name": "Golmar Sistemas de Communicacion, S.A"
    },
    {
      "name": "Grandeye Ltd"
    },
    {
      "name": "Hans India"
    },
    {
      "name": "Harcor Security Seals Pty Ltd"
    },
    {
      "name": "HashNine Managed Comm Ltd"
    },
    {
      "name": "Henan Hanwei Electronics Corp. Ltd"
    },
    {
      "name": "HID India Pvt. Ltd."
    },
    {
      "name": "Huper Laboratories Co. Ltd"
    },
    {
      "name": "I2 Limited"
    },
    {
      "name": "ICx Technologies"
    },
    {
      "name": "IJS Security"
    },
    {
      "name": "India SAFE"
    },
    {
      "name": "Indigovision"
    },
    {
      "name": "Iomniscient Pty Limited"
    },
    {
      "name": "J Mitra & Co."
    },
    {
      "name": "Kawach Protection Systems Pvt. Ltd."
    },
    {
      "name": "Keystone Electronics"
    },
    {
      "name": "KLA Systems Sdn Bhd."
    },
    {
      "name": "Kowa Co. Ltd."
    },
    {
      "name": "KSH International Co., Ltd."
    },
    {
      "name": "Lookman Electoplast Industries Ltd."
    },
    {
      "name": "M R Impex & Sons"
    },
    {
      "name": "Magnum"
    },
    {
      "name": "Mallcom (India) Limited"
    },
    {
      "name": "Mark Security Electronics Corporation"
    },
    {
      "name": "Mediatronix Pvt. Ltd."
    },
    {
      "name": "Move & Traffic Controls"
    },
    {
      "name": "N S Enterprises"
    },
    {
      "name": "Natchu Security Systems"
    },
    {
      "name": "Neotech Photoelectric Pvt. Ltd."
    },
    {
      "name": "Network Video Technologies,Inc."
    },
    {
      "name": "Nova ETS"
    },
    {
      "name": "Nova International"
    },
    {
      "name": "NVI Technologies Limited."
    },
    {
      "name": "Optex Co. Ltd."
    },
    {
      "name": "Optical Systems Design"
    },
    {
      "name": "OYTO Co Ltd"
    },
    {
      "name": "PANACOM TECHNOLOGY CORP."
    },
    {
      "name": "Panasonic Asia Pacific Pte. Ltd."
    },
    {
      "name": "Payne (India) Private Limited"
    },
    {
      "name": "Perpetuity Infotech India Pvt. Ltd."
    },
    {
      "name": "Petzl"
    },
    {
      "name": "Prama Technologies"
    },
    {
      "name": "Precision Operations Systems (India) Pvt"
    },
    {
      "name": "Prolog Systems Limited"
    },
    {
      "name": "Pyrotec India Private Limited"
    },
    {
      "name": "Qualitrade- Takex"
    },
    {
      "name": "RBH Technologies India (P) Ltd."
    },
    {
      "name": "RBM Technologies India (P) Ltd."
    },
    {
      "name": "Rifatron Co., Ltd."
    },
    {
      "name": "Romtrac"
    },
    {
      "name": "Safety & Security Industry Program Office, MOEA IDB"
    },
    {
      "name": "Sagem Defence Securite"
    },
    {
      "name": "Sambson Watchnet"
    },
    {
      "name": "Samriddhi Automation"
    },
    {
      "name": "SDIGM Inc"
    },
    {
      "name": "Seagate"
    },
    {
      "name": "Security Defense Systems"
    },
    {
      "name": "Security Dynamics"
    },
    {
      "name": "Security Today"
    },
    {
      "name": "Senstar-Stellar Corporation"
    },
    {
      "name": "SHENZHEN FUJIKAM INDUSTRY DEVELOPMENT CO. LTD"
    },
    {
      "name": "Siangsiu Industrial Corp"
    },
    {
      "name": "Siemens Building Technologies Pvt. Ltd."
    },
    {
      "name": "SJ Security systems Pvt. Ltd."
    },
    {
      "name": "SKJ Electronic Systems"
    },
    {
      "name": "Solutions Integrated Marketing Services"
    },
    {
      "name": "Somfy India Pvt. Ltd."
    },
    {
      "name": "Sony Electronics (S) Pte. Ltd."
    },
    {
      "name": "Sony India Pvt. Ltd."
    },
    {
      "name": "SPACE inc"
    },
    {
      "name": "Spur Microwave Inc."
    },
    {
      "name": "STR International Inc"
    },
    {
      "name": "Syris Technology Corp."
    },
    {
      "name": "Systems Tek India Pvt. Ltd."
    },
    {
      "name": "Taiwan Electrical & Electronic Manufactu"
    },
    {
      "name": "Taiwan Electrical and Electronic Manufacturers' Association (TEEMA )"
    },
    {
      "name": "Taylor Lock Company Ltd"
    },
    {
      "name": "Technocrat Security Systems Pvt. Ltd."
    },
    {
      "name": "TeleEye Holdings Ltd."
    },
    {
      "name": "Thakral Services India Limited"
    },
    {
      "name": "TOMST s.r.o."
    },
    {
      "name": "Tradeindia.com"
    },
    {
      "name": "TRANS PACIFIC INDUSTRIES CORP."
    },
    {
      "name": "Tritech Security Systems Pvt. Ltd."
    },
    {
      "name": "Turbo Consultancy Services Pvt. Ltd."
    },
    {
      "name": "Tyche Peripheral Systems Ltd."
    },
    {
      "name": "Unishilp Electronics (P) Ltd."
    },
    {
      "name": "Univision Enterprises (Shenzhen) Co. Ltd"
    },
    {
      "name": "UWC Electric (M) Sdn Bhd."
    },
    {
      "name": "Vectra Security Solutions Pvt. Ltd."
    },
    {
      "name": "Vetrad Systems"
    },
    {
      "name": "Videcon Plc"
    },
    {
      "name": "Vista Security Technics Pvt. Ltd."
    },
    {
      "name": "WFE TECHNOLOGY CORP,"
    },
    {
      "name": "Z Plus Security Systems Pvt. Ltd."
    }
  ]
}

=== caatdata/arms-and-security-fair-exhibitors/data/ausa-2019.json
{
  "name": "AUSA 2019",
  "series": "AUSA",
  "edition": "2019",
  "alias": "Association of the United States Army Annual Meeting 2019",
  "startDate": "2021-10-11",
  "endDate": "2021-10-13",
  "website": "https://meetings.ausa.org/annual/2021/index.cfm",
  "address": "Washington DC\nUnited States"
}

=== caatdata/arms-and-security-fair-exhibitors/data/sofex-2002.json
{
  "name": "SOFEX 2002",
  "series": "SOFEX",
  "alias": [
    "SOFEX Jordan",
    "4th Special Operations Forces Exhibition & Conference"
  ],
  "edition": "2002",
  "startDate": "2002-10-14",
  "endDate": "2002-10-17",
  "address": {
    "text": "King Abdullah I Airbase\nAmman\nJordan",
    "iso2": "JO",
    "lat": 31.991481,
    "lon": 36.0030164
  },
  "website": "https://gulfnews.com/uae/gec-to-stage-sofex-2002-in-amman-next-october-1.429053"
}

=== caatdata/arms-and-security-fair-exhibitors/data/aoc-europe-2022.json
{
  "name": "AOC Europe 2022",
  "series": "AOC Europe",
  "edition": "2022",
  "alias": [
    "Association of Old Crows 2022",
    "Electronic Warfare Europe 2022",
    "EW Europe 2022"
  ],
  "startDate": "2022-05-10",
  "endDate": "2022-05-12",
  "address": "Parc des Expositions de Montpellier\nRte de la Foire\n34470\nPÃ©rols\nFrance",
  "website": "aoceurope.org",
  "social": [
    {
      "platform": "twitter",
      "url": "https://twitter.com/AOCrows"
    },
    {
      "platform": "linkedin",
      "url": "https://www.linkedin.com/company/association-of-old-crows"
    },
    {
      "platform": "vimeo",
      "url": "https://vimeo.com/user100192111"
    }
  ],
  "exhibitorListUrl": "https://www.aoceurope.org/2022-exhibitors",
  "organiser": {
    "name": "Clarion Defence & Security Limited",
    "address": "Bedford House, Fulham High Street, London SW6 3JW, UK"
  },
  "exhibitorListDate": "2022-01-24T17:32:38+00:00",
  "exhibitor": [
    {
      "name": "Alaris Holdings",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/alaris-holdings",
      "country": "South Africa"
    },
    {
      "name": "Allen-Vanguard Ltd",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/allen-vanguard-ltd",
      "country": "United Kingdom"
    },
    {
      "name": "ApisSys",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/apissys",
      "country": "France"
    },
    {
      "name": "BIRD Aerosystems",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/bird-aerosystems",
      "country": "Israel"
    },
    {
      "name": "BSC Filters Ltd",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/bsc-filters-ltd",
      "country": "United Kingdom"
    },
    {
      "name": "Babcock Integrated Technology",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/babcock-integrated-technology",
      "country": "United Kingdom"
    },
    {
      "name": "CRFS Limited",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/crfs-limited",
      "country": "United Kingdom"
    },
    {
      "name": "Chora A/S",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/chora-a/s",
      "country": "Denmark"
    },
    {
      "name": "Clarion Defence and Security",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/clarion-defence-and-security",
      "address": "Bedford House\n69-79 Fullham High St\nFulham\nSW6 3JW\nUnited Kingdom",
      "website": "https://www.clarion-defence.com/"
    },
    {
      "name": "Communications Audit UK Ltd.",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/communications-audit-uk-ltd",
      "country": "United Kingdom"
    },
    {
      "name": "Decodio AG",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/decodio-ag",
      "country": "Switzerland"
    },
    {
      "name": "ELDES s.r.l",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/eldes-srl",
      "address": ".\n.\nItaly"
    },
    {
      "name": "ELETTRONICA S.P.A.",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/elettronica-spa",
      "country": "Italy"
    },
    {
      "name": "ELTA Systems",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/elta-systems",
      "country": "Israel"
    },
    {
      "name": "ERA a.s.",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/era-as",
      "country": "Czech Republic"
    },
    {
      "name": "ERZIA",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/erzia",
      "country": "Spain"
    },
    {
      "name": "Elbit Systems EW and SIGINT",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/elbit-systems-ew-and-sigint",
      "address": ".\n.\nIsrael"
    },
    {
      "name": "Empower RF Systems",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/empower-rf-systems",
      "country": "United States"
    },
    {
      "name": "Epiq Solutions",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/epiq-solutions",
      "country": "United States"
    },
    {
      "name": "FS Antennentechnik GmbH",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/fs-antennentechnik-gmbh",
      "country": "Germany"
    },
    {
      "name": "FinFisher GmbH",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/finfisher-gmbh",
      "country": "Germany"
    },
    {
      "name": "Galleon Embedded Computing AS",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/galleon-embedded-computing-as",
      "country": "Norway"
    },
    {
      "name": "Glenair France",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/glenair-france",
      "country": "France"
    },
    {
      "name": "HENSOLDT Holding Germany GmbH",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/hensoldt-holding-germany-gmbh",
      "country": "Germany"
    },
    {
      "name": "Huber + Suhner",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/huber-suhner",
      "address": ".\n.\nSwitzerland"
    },
    {
      "name": "Interface Concept",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/interface-concept",
      "country": "France"
    },
    {
      "name": "Leonardo MW Ltd",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/leonardo-mw-ltd",
      "country": "United Kingdom"
    },
    {
      "name": "MBDA FRANCE",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/mbda-france",
      "country": "France"
    },
    {
      "name": "Microwave Specialty Company",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/microwave-specialty-company",
      "country": "United States"
    },
    {
      "name": "NSI-MI Technologies",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/nsi-mi-technologies",
      "country": "United States"
    },
    {
      "name": "Novator Solutions AB",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/novator-solutions-ab",
      "country": "Sweden"
    },
    {
      "name": "Ocupoint",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/ocupoint",
      "country": "United States"
    },
    {
      "name": "PROCITEC GmbH",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/procitec-gmbh",
      "country": "Germany"
    },
    {
      "name": "Photonis Defense, Inc.",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/photonis-defense-inc",
      "country": "United States"
    },
    {
      "name": "RUAG Schweiz AG",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/ruag-schweiz-ag",
      "country": "Switzerland"
    },
    {
      "name": "Rohde & Schwarz GmbH & Co. KG",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/rohde-schwarz-gmbh-co-kg",
      "country": "Germany"
    },
    {
      "name": "SAAB AB..",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/saab-ab",
      "country": "Sweden"
    },
    {
      "name": "Sch'nhofer Sales and Engineering GmbH",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/schnhofer-sales-and-engineering-gmbh",
      "country": "Germany"
    },
    {
      "name": "Swissto12",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/swissto12",
      "country": "Israel"
    },
    {
      "name": "TCI International",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/tci-international",
      "country": "United States"
    },
    {
      "name": "TMD Technologies",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/tmd-technologies",
      "country": "United Kingdom"
    },
    {
      "name": "Textron Systems",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/textron-systems",
      "country": "United States"
    },
    {
      "name": "Thales Communications & Security",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/thales-communications-security",
      "country": "France"
    },
    {
      "name": "Ultra",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/ultra",
      "country": "United Kingdom"
    },
    {
      "name": "VIAVI Solutions, Inc.",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/viavi-solutions-inc",
      "country": "United States"
    },
    {
      "name": "WORK Microwave",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/work-microwave",
      "country": "Germany"
    },
    {
      "name": "boger electronics GmbH",
      "exhibitorUrl": "https://www.aoceurope.org/exhibitors/boger-electronics-gmbh",
      "country": "Germany"
    }
  ]
}
